### ISSUE TITLE
Extending CHIPS to localStorage as well

### ISSUE THREAD

**Issue by nir-walkme** [WICG/CHIPS#23]
Hi

I propose that CHIPS to be extended localStorage as well.

The use case: A complex web application is comprised of a top window from domain exampleA.com and a cross-domain iframe from domain exampleB.com. The iframe is visible and the user is interacting with it.
The iframe contains a "javascript widget". This widget is using cookies/localStorage for local persistence.  For example: Remember if the user opened the widget, so in next page view, the widget would be open.

With third-party cookies being blocked, it is no longer possible to store cookies/localStorage in a cross-domain iframe so the widget would stop working. If it would be possible for the "javascript widget" to store localStorage in a partitioned way, the "javascript widget" would still be able to work (not perfectly, because its state would not be shared cross-domain, but still better than nothing).

Thanks

**Comment by DCtheTall** [comment]
Hi @nir-walkme, I think what you are referring to here is covered by the [Storage Partitioning](https://github.com/privacycg/storage-partitioning) proposal, which is separate from CHIPS (which only focuses on cookies).
