### ISSUE TITLE
How to tell if Chrome `partitioned-cookies` flag is working

### ISSUE THREAD

**Issue by remko** [WICG/CHIPS#41]
I enabled the local Chrome flag of partitioned attributes using `chrome://flags/#partitioned-cookies` in Chrome 102, but I don't notice any changes. 

More specifically:

- Non-partioned cookies are still being sent in a third party context (i.e. in an iframe). Cookies that were returned in first-party context (i.e. on toplevel) with the `Partitioned` flag are also still being sent in the iframe. Am I correct that this is expected? (I.e. enabling the `partitioned` flag isn't strict in enforcing that all cookies in partitioned contexts are partitioned?)

- When setting the `Partitioned` property on a (server-sent) cookie, I don't see anything happening in the UI. I was expecting something in the 'Partition Key' column in Application > Cookies, but the column remains empty.

Is there any way of telling that I turned on partitioned cookies, and that they are working? Did I miss something and didn't enable them properly?

**Comment by DCtheTall** [comment]
Hi @remko, thank you for your interest in CHIPS and the origin trial in Chrome.

This repository is meant to discuss the design of the Partitioned attribute more generally than just the Chrome-specific implementation. For future reference, please file Chrome-specific issues at https://crbug.com or in the [Privacy Sandbox Dev Support discussions page](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/discussions).

To answer your questions:

- Unpartitioned cross-site cookies are still sent when partitioned cookies are enabled, nor does enabling the feature impact unpartitioned cross-site cookies in any way. Partitioned cookies are an opt-in technology only.
- Chances are you need to also pass the `chrome://flags#partitioned-cookies-bypass-origin-trial` flag as well to bypass the origin trial running until the end of M104.
