### ISSUE TITLE
Top level site partitioned cookies cleared by Javascript API

### ISSUE THREAD

**Issue by michael-oneill** [WICG/CHIPS#7]
Generating a Clear-Site-Data header may be difficult in many scenarios. There should be a way to delete partitioned cookies in script also,

At the moment sites can remove top-level cookies by writing to document.cookie, can clear localStorage etc., none of this is available for partitioned storage, 

There was a Chrome experimental API for this, it should be made a standard.

**Comment by DCtheTall** [comment]
> There should be a way to delete partitioned cookies in script also

This sounds reasonable to me if we do not end up requiring that `Partitioned` cookies also have `HttpOnly`.

> At the moment sites can remove top-level cookies by writing to document.cookie, can clear localStorage etc., none of this is available for partitioned storage

IIUC if we do allow `Partitioned` cookies to be accessed in scripts, then an embedded frame could use `document.cookie` or the [CookieStore API](https://developer.mozilla.org/en-US/docs/Web/API/Cookie_Store_API) to clear their cookies for _only_ that top-level partition.

**Comment by michael-oneill** [comment]
Yes it makes sense that embedded iframes can write to their own top-level partitioned cookies (unless HttpOnly of course), but I was only suggesting a top-level contexts being able to clear all storage, in its own origin as well as partitioned by any embedded origin, which the proposal already allows via the Clear-Site-Data response header.
We could slightly extend it by allowing top-levels to set partitioned cookies in embedded origins but only with the agreement of the embedded origin, which is already available as a capability via postMessage (the embedded context could refuse to recognise the message). 
This would aloow communication from top-level frames to embeds even when there was no embedded iframes e.g. for images etc.. Maybe the embed would allow the capability fia a Permissions-Policy header, with the target origin set by the domain property in [CookieStore API](https://developer.mozilla.org/en-US/docs/Web/API/Cookie_Store_API).
This could enabl the efficient communication of user consent state from top-level frames to subresources
